### ISSUE TITLE
unable to call endpoint

### ISSUE THREAD

**Issue by arorasahil1234** [gsdriver/restaurant-finder#1]
I am really not sure but i think i am getting the error unable to call endpoint because of api access i have copied the code and just change app_id ,i tried to sign up to yelp account but that site was down 
could you please help me out here ?

**Comment by arorasahil1234** [comment]
alexa open skill name 
Welcome to Restaurant Finder. You can find restaurants by type of cuisine, price range, or with high Yelp reviews. For example, you can say Find a cheap Chinese restaurant in Seattle. How can I help you?

I do get this message but when i ask for good restaurants  alexa trows this error

**Comment by gsdriver** [comment]
You need to change config.token in src\config.js with your Yelp token.  You can get a Yelp token at https://www.yelp.com/fusion.  I just checked, and their site is working for me.

**Comment by arorasahil1234** [comment]
thank you so much , i figured that out , was not able to sign up but now i can :) however  the skill read the restaurant names but when i say the correponding number it goes on reading the name only it does not revert the detials like phone number review etc
Reading 5 restaurants. **You can ask for more details by saying the corresponding restaurant number or say More to hear more results. 1 ... A + Hong Kong Kitchen. 2 ... Zheng Cafe. 3 ... Harbor City Restaurant. 4 ... Din Tai Fung. 5 ... Din Tai Fung.**

**Comment by gsdriver** [comment]
That's right - there are two phases to getting restaurant details.  First you hear a list of restaurants (and you can say "more" or "back" to hear them five at a time).  When you hear one you want full details on, including Yelp review and phone number, you say "tell me about X" (X being the number in the list), which sends a DetailsIntent to the function.

**Comment by arorasahil1234** [comment]
I am sorry ,just one last question am very new to this technology what to do if I want to read  few of reviews ?
Do share your inputs thank you so much 😊

Regards, Sahil Arora

**Comment by gsdriver** [comment]
You can get the last three reviews from the Yelp API - it's documented here: https://www.yelp.com/developers/documentation/v3/business_reviews
